### ISSUE TITLE
Failed to load a language-ace package grammar (syntax errors)

### ISSUE THREAD

**Issue by peterkappus** [pariz/atom-ace#2]
HI there, 

Just tried installing the language-ace package but getting syntax errors (see below).

Thanks!
Peter

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [language-ace](https://github.com/pariz/atom-ace) package 1.1.0

### Stack Trace

Failed to load a language-ace package grammar

```
At /Users/peterk/.atom/packages/language-ace/grammars/ace.cson: Syntax error on line 208, column 12: Unexpected StringWithInterpolations in /Users/peterk/.atom/packages/language-ace/grammars/ace.cson

SyntaxError: /Users/peterk/.atom/packages/language-ace/grammars/ace.cson: Syntax error on line 208, column 12: Unexpected StringWithInterpolations
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:219:19)
    at Value (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:102:18)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at addProperty (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:152:21)
    at Array.reduce (native)
    at Obj (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:145:34)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at Value (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:102:18)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at addProperty (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:152:21)
    at Array.reduce (native)
    at Obj (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:145:34)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at Value (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:102:18)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at addProperty (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:152:21)
    at Array.reduce (native)
    at Obj (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:145:34)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at Value (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:102:18)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at Block (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:99:18)
    at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:221:18)
    at Object.parse (/Applications/Atom.app/Contents/Resources/app/node_modules/cson-parser/lib/parse.js:227:22)
    at parseObject (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:46:29)
    at parseContents (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:106:22)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:226:30
    at FSReqWrap.oncomplete (fs.js:112:15)
  at /packages/language-ace/grammars/ace.cson:1:1
```

### Commands

```
     -1:25.8.0 settings-view:open (input.hidden-input)
  2x -1:17.8.0 core:select-all (input.hidden-input)
     -0:46.1.0 core:backspace (input.hidden-input)
     -0:45.1.0 core:confirm (input.hidden-input)
     -0:33 pane:show-next-item (input.hidden-input)
  2x -0:31.2.0 pane:show-previous-item (input.hidden-input)
  2x -0:29.6.0 pane:show-next-item (input.hidden-input)
     -0:28.7.0 pane:show-previous-item (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
color-picker 2.2.5 
cucumber 0.6.0 
language-ace 1.1.0 
language-docker 1.1.8 
language-slim 0.5.0 
minimap 4.29.7 
pigments 0.40.2 
rails-partials 0.9.2 
seti-ui 1.9.0 
vim-mode-plus 0.96.2 
```

**Comment by michalsz** [comment]
I had the same issue with the package.

**Comment by nakabonne** [comment]
I have too.

**Comment by purrloftruth** [comment]
I appreciate that this may have been fixed, but it seems like a new version was never pushed to the package manager...

**Comment by kaamoss** [comment]
This still seems to be an issue in the current package version.
